# Cache the python packages
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - lint
  - test
  - document
  - deploy

flake8:
  stage: lint
  allow_failure: true
  script:
    - pip install flake8 flake8-junit-report
    - retval=0
    - flake8 --output-file flake8.txt torchmm/ || retval=$?
    - flake8_junit flake8.txt flake8_junit.xml
    - cat flake8.txt
    - exit "$retval"
  artifacts:
    when: always
    reports:
      junit: flake8_junit.xml
  tags:
    - pytorch

pytest:
  stage: test
  allow_failure: false
  script:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
      #- pip install tox
      #- tox
    - python -m pytest
  artifacts:
    when: always
    reports:
      junit: output.xml
  tags:
    - pytorch

sphinx:
  stage: document
  dependencies:
    - flake8
  script:
    - pip install -r docs/doc-requirements.txt
    - apt-get update
    - apt-get install make
    - cd docs
    - make html
    - mv _build/html/ ../sphinx
  artifacts:
    paths:
      - sphinx
  tags:
    - pytorch
  only:
    - master

coverage:
  stage: document
  allow_failure: true
  dependencies:
    - pytest
  script:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - retval=0
    - coverage run --source torchmm -m pytest || retval=$?
    - coverage html -d coverage
    - coverage report
      # - exit "$retval"
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - coverage
  tags:
    - pytorch

pages:
  stage: deploy
  dependencies:
    - sphinx
    - coverage
  script:
    - mv sphinx public/
    - mv coverage public/coverage
  environment:
    name: pages
    url: https://chris.maclellan.hq-git.soartech.com/TorCHmM
  artifacts:
    paths:
      - public
  tags: 
    - pytorch
  only:
    - master

pypi:
  stage: deploy
  dependencies:
    - coverage
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url https://nexus.soartech.com:8443/nexus/repository/pypi-internal/ dist/*
  tags:
    - pytorch
  only:
    - master
