before_script:
  - apk --no-cache add git python3 py3-pip py3-numpy 

stages:
  - lint
    #   - test
  - document
  - deploy

flake8:
  stage: lint
  allow_failure: true
  script:
    - pip3 install flake8 flake8-junit-report
    - retval=0
    - flake8 --output-file flake8.txt foo/ || retval=$?
    - flake8_junit flake8.txt flake8_junit.xml
    - exit "$retval"
  artifacts:
    when: always
    reports:
      junit: flake8_junit.xml
  tags:
    - html

      # pytest:
      #   stage: test
      #   script:
      #     - pip3 install -r requirements.txt
      #     - pip3 install -r test-requirements.txt
      #       #- pip3 install tox
      #       #- tox
      #     - python3 -m pytest
      #   artifacts:
      #     when: always
      #     reports:
      #       junit: output.xml
      #   tags:
      #     - html

sphinx:
  stage: document
  dependencies:
    - flake8
  script:
    - pip3 install -r docs/doc-requirements.txt
    - apk --no-cache add make
    - cd docs
    - make html
    - mv _build/html/ ../sphinx
  artifacts:
    paths:
      - sphinx
  tags:
    - html
  only:
    - master

      # coverage:
      #   stage: document
      #   dependencies:
      #     - pytest
      #   script:
      #     - pip3 install -r test_requirements.txt
      #     - pip3 install coverage
      #     - coverage run --source hmm_torch -m pytest
      #     - coverage html -d coverage
      #     - coverage report
      #   coverage: '/\d+\%\s*$/'
      #   artifacts:
      #     paths:
      #       - coverage
      #   tags:
      #     - html

pages:
  stage: deploy
  dependencies:
    - sphinx
      # - coverage
  script:
    - mv sphinx public/
    # - mv coverage public/coverage
  environment:
    name: pages
    url: https://git.hq-git.soartech.com/TorCHmM/
  artifacts:
    paths:
      - public
  tags: 
    - html
  only:
    - master
